services:
  database:
    image: postgres:16-alpine
    container_name: db-autoflex
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: autoflex
      POSTGRES_PASSWORD: autoflex
    ports:
      - "5432:5432"